---
sidebar: sidebar 
permalink: task-manage-private-google-cloud.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, google cloud 
summary: 管理您的通用和超大规模特定、端到端私人优惠流程以及适用于 AWS、Azure 和 Google Cloud 的NetApp智能服务接受和激活指南。 
---
= 接受并配置NetApp Console的 Google Cloud 专属优惠
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 


[role="lead"]
接受 Google Cloud 控制台中NetApp Console列表的 Marketplace 私人优惠。在控制台中配置 Google Cloud 凭据。

.开始之前
* 与NetApp销售人员合作创建私人优惠。您的销售团队必须向您提供优惠链接。
* 您的结算帐户不得处于免费试用状态。免费试用帐户不能接受私人优惠。如果您尝试使用试用计费帐户，您将收到错误消息并需要NetApp云团队的帮助。
* 接受该优惠需要以下 Google Cloud 权限：
+
** `roles/billing.admin`针对目标 Cloud Billing 帐号或 Google Cloud 组织
** `roles/viewer`对于计入 Cloud Billing 帐户的项目






== 接受 Google Cloud 中的私人优惠

一个 Google Cloud 项目只能与一个 Marketplace 订阅关联。如果您想对同一个 Google Cloud 项目中的工作负载使用两个不同的订阅，则必须创建两个单独的控制台帐户 - 每个订阅一个。

[IMPORTANT]
====
您必须完成所有步骤才能激活您的私人优惠。跳过这些步骤可能会导致诸如重复充电等问题。

如果您发现报价条款、定价或细节存在差异，或者您不确定接受哪个报价，请不要接受该报价。请联系您的NetApp客户团队以获取说明。

====
[NOTE]
====
如果您已经拥有有效的 PAYGO 订阅或修改后的私人优惠，则只需执行接受步骤。在这些情况下，市场会在同一列表中更新计划并保留相同的订阅 ID，因此控制台中的订阅关联保持不变。

====
.步骤
. 单击NetApp销售团队提供的私人优惠激活链接。该链接应类似于以下内容：
`https://console.cloud.google.com/marketplace/private-offers/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee`
. 您将被重定向到 Google Cloud Marketplace，您可以在其中查看优惠详情：
+
.. **结算账户**
.. **产品**： NetApp Console
.. **优惠详情**
.. **定价**
+
[NOTE]
====
仔细检查计划细节、期限和定价。如果有任何不正确的地方，请不要接受该提议。请联系您的NetApp客户团队以获取修改。

====


. 确认信息准确，接受条款，然后单击**接受**。
. 创建订阅时会出现一个加载图标。
. 成功创建订阅后，会弹出窗口显示：*您的订单请求已发送至NetApp, Inc.*
. 单击**向 NETAPP, Inc. 注册**。您将被重定向到NetApp Console以完成订阅配置。如果您组织中的另一个人接受了专属优惠：
+
.. 在 Google Cloud Marketplace 中，转到**订单**。
.. 找到状态为**待定**的报价。
.. 单击三点菜单并选择**向NetApp, Inc. 注册**


. 您将被重定向至 `https://console.netapp.com`并提示登录。
. 登录后，您将被重定向至 `https://console.netapp.com/licenses/overview`。将显示一个弹出窗口，您必须执行以下操作：
+
.. 输入“SaaS 市场订阅”的显示名称。
.. 选择应该有权访问订阅的控制台**帐户**。
.. 或者，如果您想在一个控制台帐户中自动替换现有的 Marketplace 订阅，您可以启用**替换现有订阅**。
+
[NOTE]
====
*** 此替换选项仅限于单个控制台帐户。
*** 如果您需要将多个控制台帐户与同一个 Marketplace 订阅关联，则必须手动配置其他帐户。


====


. 点击**关联**。
. 填写此表格，将订阅与您的 Console 组织关联起来。然后，点击**关联**。
. 关联订阅后，导航并选择“账单偏好设置”选项卡。
. 查看应用商店的订阅选项。
. 选择您要计费的商城订阅服务。这仅适用于存在多个选项的情况。
. 选择**保存更改**。
. 如果需要跨多个超大规模数据中心进行多个订阅，请重复这些步骤。


有关市场订阅和直接许可计费的更多信息，请参阅 link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["账单偏好文档"]。
